version: '3'
services:
  backend:
    image: esgforum-docker-backend:latest
    container_name: esg-backend-laravel
    ports:
      - 9000:9000
    env_file:
      - .env

  frontend:
    image: esgforum-docker-frontend:latest
    container_name: esg-web-react
    ports:
      - 8080:80
    environment:
      - REACT_APP_API_URL=http://backend/api

  proxy:
    image: nginx:1.24.0
    container_name: esg-proxy-nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - frontend
      - backend

  db:
    image: mariadb:10.11
    container_name: esg-db-mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - .mysql.env
