# docker copmose build시 submodule을 가져오고 .env 파일도 넣어줘야 가능합니다.
version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: esg-backend-laravel
    ports:
      - 9000:9000
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: esg-web-react
    ports:
      - 8080:80
    environment:
      - TZ=Asia/Seoul
      - REACT_APP_API_URL=http://localhost:9000

  proxy:
    image: nginx:1.24.0
    container_name: esg-proxy-nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - frontend
      - backend

  db:
    image: mariadb:10.11
    container_name: esg-db-mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .mysql.env
